# Ruff configuration file for IDE integration
# This ensures your IDE formatter matches `make lint` requirements

line-length = 88
target-version = "py311"
exclude = [
    ".git",
    ".venv", 
    "__pycache__",
    "build",
    "dist",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
]

[lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings  
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "RUF",  # ruff-specific rules
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "PIE",  # flake8-pie
    "SIM",  # flake8-simplify
    "TCH",  # flake8-type-checking
]

ignore = [
    "RUF006",  # Store a reference to the return value of `asyncio.create_task` - Allow fire-and-forget tasks
    "E501",    # Line too long - handled by formatter
    "W505",    # Doc line too long - handled by formatter
    "E203",    # Whitespace before ':' - conflicts with ruff formatter
    "E231",    # Missing whitespace after ',' - handled by formatter
    "SIM103",  # Return condition directly - sometimes explicit is clearer
    "SIM105",  # Use contextlib.suppress - prefer explicit exception handling
    "SIM108",  # Use ternary operator - sometimes if/else is clearer
]

[lint.isort]
known-first-party = ["bot"]
force-sort-within-sections = true
split-on-trailing-comma = true

[lint.per-file-ignores]
"tests/*" = ["S101"]  # Allow assert statements in tests

[format]
quote-style = "double"
indent-style = "space" 
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"