# Trading Bot Configuration
# Non-secret settings that can be version controlled

trading:
  # Symbol configuration
  symbol_src: ADAUSDT      # Binance source symbol
  symbol_dst: ADAUSDM      # DeltaDeFi destination symbol

  # Multi-layer strategy parameters
  base_spread_bps: 8       # Starting spread from reference price (basis points)
  tick_spread_bps: 10      # Incremental spread between layers (basis points)
  num_layers: 10           # Number of layers per side
  layer_liquidity_multiplier: 1.0  # Liquidity growth factor per layer (100% growth)
  total_liquidity: 5000.0  # Total liquidity to distribute across all layers

  # Legacy spread configuration (for backwards compatibility)
  anchor_bps: 5            # Distance from Binance BBO
  venue_spread_bps: 3      # Cross-venue risk buffer

  # Order configuration
  qty: 0.0                 # Set to 0 to use calculated sizing based on deployable capital
  side_enable: ["bid", "ask"]  # Which sides to quote
  min_quote_size: 10.0     # Minimum quote size (fallback for very small calculations)
  max_open_notional: 5000.0  # Maximum open notional

  # Asset ratio management parameters
  target_asset_ratio: 1.0  # Target USDM:ADA value ratio (1.0 = 1:1)
  ratio_tolerance: 0.1     # Acceptable deviation from target ratio (10%)
  spread_adjustment_factor: 2.0    # Multiplier for spread adjustment when out of ratio
  liquidity_adjustment_factor: 1.5 # Multiplier for liquidity size adjustment when out of ratio
  use_full_capital: true   # Deploy 100% of available capital for market making
  capital_reserve_ratio: 0.02 # Percentage of capital to keep as reserve (2%)

  # Timing controls (milliseconds)
  min_requote_ms: 100      # Minimum time between requotes
  stale_ms: 5000          # Market data staleness threshold
  requote_tick_threshold: 0.0001  # Minimum price change for requote

  # Quote management
  quote_ttl_ms: 2000      # Quote time-to-live before replacement (2 seconds)
  enable_aggressive_replacement: true  # Cancel existing orders immediately on price moves

risk:
  # Position limits
  max_position_size: 5000.0   # Maximum position in base units
  max_daily_loss: 1000.0      # Daily loss limit
  max_skew: 2000.0           # Maximum position skew

  # Risk controls
  enable_oms: true           # Enable order management system
  max_open_orders: 50        # Maximum number of open orders (increased for multi-layer with buffer for replacement)
  emergency_stop: false      # Emergency stop flag

system:
  # Performance settings
  max_orders_per_second: 5.0    # Rate limiting

  # Database settings
  enable_wal_mode: true         # SQLite WAL mode
  connection_pool_size: 5       # DB connection pool

  # Order cleanup settings
  cleanup_unregistered_orders: true  # Enable automatic cleanup of unregistered orders
  cleanup_check_interval_ms: 30000   # Interval for checking unregistered orders (30 seconds)
  order_registration_timeout_ms: 5000 # Timeout for order registration in database (5 seconds)

  # Monitoring
  health_check_interval: 30     # Health check frequency (seconds)
  metrics_export_interval: 60   # Metrics export frequency (seconds)
